# Generated by Django 5.0.7 on 2025-12-10 02:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("comunidades", "0001_initial"),
        ("periodos", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Proyecto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
                ("descripcion", models.TextField(default="")),
                ("fecha_inicio", models.DateField(blank=True, null=True)),
                ("fecha_fin", models.DateField(blank=True, null=True)),
                (
                    "presupuesto_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("estado", models.CharField(default="Pendiente", max_length=50)),
                (
                    "total_rendido",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "estado_rendicion",
                    models.CharField(default="Pendiente", max_length=50),
                ),
                (
                    "acta",
                    models.FileField(
                        blank=True, null=True, upload_to="proyectos/actas/"
                    ),
                ),
                (
                    "cotizaciones",
                    models.FileField(
                        blank=True, null=True, upload_to="proyectos/cotizaciones/"
                    ),
                ),
                (
                    "elegido",
                    models.FileField(
                        blank=True, null=True, upload_to="proyectos/elegido/"
                    ),
                ),
                (
                    "comunidad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="comunidades.comunidad",
                    ),
                ),
                (
                    "periodo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="periodos.periodo",
                    ),
                ),
            ],
        ),
    ]
