# Generated by Django 5.0.7 on 2025-12-10 05:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proyectos", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="proyecto",
            name="estado",
            field=models.CharField(
                choices=[
                    ("borrador", "Borrador"),
                    ("revision_interna", "En Revisión Interna"),
                    ("revision_cpa", "En Revisión CPA"),
                    ("observaciones", "Con Observaciones"),
                    ("aprobado", "Aprobado"),
                    ("ejecucion", "En Ejecución"),
                    ("cierre", "Cierre"),
                ],
                default="borrador",
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="HistorialEstado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "estado_anterior",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("borrador", "Borrador"),
                            ("revision_interna", "En Revisión Interna"),
                            ("revision_cpa", "En Revisión CPA"),
                            ("observaciones", "Con Observaciones"),
                            ("aprobado", "Aprobado"),
                            ("ejecucion", "En Ejecución"),
                            ("cierre", "Cierre"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "estado_nuevo",
                    models.CharField(
                        choices=[
                            ("borrador", "Borrador"),
                            ("revision_interna", "En Revisión Interna"),
                            ("revision_cpa", "En Revisión CPA"),
                            ("observaciones", "Con Observaciones"),
                            ("aprobado", "Aprobado"),
                            ("ejecucion", "En Ejecución"),
                            ("cierre", "Cierre"),
                        ],
                        max_length=50,
                    ),
                ),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                ("comentario", models.TextField(blank=True)),
                (
                    "proyecto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historial",
                        to="proyectos.proyecto",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
