# Generated by Django 5.0.7 on 2025-12-10 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proyectos", "0002_alter_proyecto_estado_historialestado"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="proyecto",
            name="acta",
        ),
        migrations.RemoveField(
            model_name="proyecto",
            name="cotizaciones",
        ),
        migrations.RemoveField(
            model_name="proyecto",
            name="elegido",
        ),
        migrations.AddField(
            model_name="proyecto",
            name="beneficiarios_estimados",
            field=models.PositiveIntegerField(
                default=0, help_text="Número de personas beneficiadas"
            ),
        ),
        migrations.AddField(
            model_name="proyecto",
            name="fecha_firma_presidente",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="proyecto",
            name="firma_presidente",
            field=models.BooleanField(
                default=False, help_text="Aprobación digital simple del Presidente"
            ),
        ),
        migrations.AddField(
            model_name="proyecto",
            name="justificacion",
            field=models.TextField(
                blank=True, default="", help_text="Por qué es necesario este proyecto"
            ),
        ),
        migrations.AddField(
            model_name="proyecto",
            name="objetivos",
            field=models.TextField(
                blank=True, default="", help_text="Objetivos principales del proyecto"
            ),
        ),
        migrations.AddField(
            model_name="proyecto",
            name="quorum_asamblea",
            field=models.PositiveIntegerField(
                default=0, help_text="Número de asistentes en el Acta"
            ),
        ),
    ]
