# Generated by Django 5.0.7 on 2025-12-10 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "proyectos",
            "0003_remove_proyecto_acta_remove_proyecto_cotizaciones_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Remesa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "monto_solicitado",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("fecha_solicitud", models.DateField(auto_now_add=True)),
                ("motivo", models.TextField()),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("aprobado", "Aprobado"),
                            ("rechazado", "Rechazado"),
                            ("pagado", "Pagado"),
                        ],
                        default="pendiente",
                        max_length=20,
                    ),
                ),
                ("fecha_pago", models.DateField(blank=True, null=True)),
                (
                    "comprobante_transferencia",
                    models.FileField(
                        blank=True, null=True, upload_to="remesas/comprobantes/"
                    ),
                ),
                (
                    "proyecto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="remesas",
                        to="proyectos.proyecto",
                    ),
                ),
            ],
        ),
    ]
