# Generated by Django 5.0.7 on 2025-12-10 06:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proyectos", "0004_remesa"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReporteAvance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_reporte", models.DateField(auto_now_add=True)),
                (
                    "porcentaje_avance",
                    models.PositiveIntegerField(
                        help_text="Porcentaje de avance físico (0-100)"
                    ),
                ),
                ("observaciones", models.TextField()),
                (
                    "foto_avance",
                    models.ImageField(blank=True, null=True, upload_to="avances/"),
                ),
                (
                    "autor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "proyecto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reportes_avance",
                        to="proyectos.proyecto",
                    ),
                ),
            ],
        ),
    ]
