# Generated by Django 5.2.7 on 2026-01-15 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0005_reporteavance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Remesa',
        ),
    ]
