# Generated by Django 5.0.7 on 2025-12-10 02:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("comunidades", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="comunidad",
            name="usuario",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comunidades",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="consejo",
            name="comunidad",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="comunidades.comunidad"
            ),
        ),
        migrations.AddField(
            model_name="socio",
            name="comunidad",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="comunidades.comunidad"
            ),
        ),
        migrations.AddField(
            model_name="socio",
            name="consejo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="comunidades.consejo",
            ),
        ),
    ]
