# Generated by Django 5.0.7 on 2025-12-10 02:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("beneficiarios", "0001_initial"),
        ("comunidades", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="beneficiario",
            name="comunidad",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="comunidades.comunidad"
            ),
        ),
    ]
