# Generated by Django 5.0.7 on 2025-12-10 02:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auditores", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditorReporte",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField()),
                ("descripcion", models.TextField()),
                (
                    "auditor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="auditores.auditor",
                    ),
                ),
            ],
        ),
    ]
