# Generated by Django 5.0.7 on 2025-12-10 02:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("comunidades", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Periodo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
                ("fecha_inicio", models.DateField()),
                ("fecha_fin", models.DateField()),
                (
                    "monto_asignado",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "monto_anterior",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("activo", models.BooleanField(default=True)),
                (
                    "comunidad",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="periodos",
                        to="comunidades.comunidad",
                    ),
                ),
            ],
        ),
    ]
