# Generated by Django 5.0.7 on 2025-12-10 02:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("documentos", "0001_initial"),
        ("proyectos", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Rendicion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descripcion", models.TextField(blank=True, null=True)),
                ("monto_rendido", models.DecimalField(decimal_places=2, max_digits=12)),
                ("fecha_rendicion", models.DateField()),
                (
                    "documentos_adjuntos",
                    models.ManyToManyField(
                        blank=True,
                        related_name="rendiciones_adjuntas",
                        to="documentos.documento",
                    ),
                ),
                (
                    "proyecto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="proyectos.proyecto",
                    ),
                ),
            ],
        ),
    ]
