# Generated by Django 5.0.7 on 2025-12-10 06:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rendiciones", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="rendicion",
            name="estado",
            field=models.CharField(
                choices=[
                    ("pendiente", "Pendiente"),
                    ("aprobado", "Aprobado"),
                    ("observado", "Con Observaciones"),
                    ("rechazado", "Rechazado"),
                ],
                default="pendiente",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="rendicion",
            name="fecha_revision",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="rendicion",
            name="observacion",
            field=models.TextField(
                blank=True, help_text="Observaciones del auditor/CPA", null=True
            ),
        ),
        migrations.AddField(
            model_name="rendicion",
            name="revisor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rendiciones_revisadas",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
