# Generated by Django 5.2.7 on 2026-01-15 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rendiciones', '0002_rendicion_estado_rendicion_fecha_revision_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rendicion',
            name='numero_documento',
            field=models.CharField(blank=True, help_text='Número de factura o boleta', max_length=50, null=True),
        ),
    ]
