# Generated by Django 5.2.7 on 2026-01-15 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rendiciones', '0003_rendicion_numero_documento'),
    ]

    operations = [
        migrations.AddField(
            model_name='rendicion',
            name='comprobante_traspaso',
            field=models.FileField(blank=True, help_text='Comprobante de transferencia al proveedor', null=True, upload_to='comprobantes_pago/'),
        ),
        migrations.AlterField(
            model_name='rendicion',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('observado', 'Con Observaciones'), ('rechazado', 'Rechazado'), ('pagado', 'Pagado')], default='pendiente', max_length=20),
        ),
    ]
