# Generated by Django 5.0.7 on 2025-12-10 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="rol",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("auditor", "Auditor"),
                    ("usuario", "Usuario"),
                    ("directorio", "Directorio Comunidad"),
                    ("presidente", "Presidente Comunidad"),
                    ("ito", "ITO / Responsable"),
                    ("cpa", "CPA Revisor"),
                ],
                default="usuario",
                max_length=20,
            ),
        ),
    ]
