# Generated by Django 5.0.7 on 2025-12-10 02:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("proyectos", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Documento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_subida", models.DateTimeField(auto_now_add=True)),
                ("nombre", models.CharField(max_length=255)),
                ("tipo", models.CharField(max_length=50)),
                ("archivo", models.FileField(upload_to="documentos/")),
                ("descripcion", models.TextField(blank=True)),
                (
                    "proyecto",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="proyectos.proyecto",
                    ),
                ),
            ],
        ),
    ]
